# Use nginx alpine as it's lightweight
FROM nginx:alpine

# Copy static files
COPY ./ /usr/share/nginx/html/

# Copy nginx configuration if you need custom config
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80
